CREATE DATABASE UNAPEC;
USE UNAPEC;

CREATE TABLE EMPLOYEE(
    ID int NOT NULL AUTO_INCREMENT,
    DOCUMENT_NUMBER varchar(20) NOT NULL,
    FIRST_NAME varchar(50),
    LAST_NAME varchar(50),
    ACCOUNT_NUMBER varchar(20) NOT NULL,
    CRUDE_SALARY decimal(18,2),
    PRIMARY KEY (ID)
);

CREATE TABLE PAYROLL(
    ID int NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID int not null,
    PAYROLL_DATE DATETIME,
    ISR_DISCOUNT decimal(18,2),
    AFP_DISCOUNT decimal(18,2),
    HEALTH_INSURANCE decimal(18,2),
    OTHERS_DISCOUNTS decimal(18,2),
    TOTAL_DISCOUNTS decimal(18,2),
    NET_SALARY decimal(18,2),
    PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_PAYROLL FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES EMPLOYEE(ID)
);